package com.syd.goods.model;

public class ContactModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.contact_id
     *
     * @mbg.generated
     */
    private Integer contactId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.telephone
     *
     * @mbg.generated
     */
    private Integer telephone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.phone
     *
     * @mbg.generated
     */
    private Integer phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.wx
     *
     * @mbg.generated
     */
    private String wx;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.qq
     *
     * @mbg.generated
     */
    private String qq;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contact.QR_code
     *
     * @mbg.generated
     */
    private String qrCode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.contact_id
     *
     * @return the value of contact.contact_id
     *
     * @mbg.generated
     */
    public Integer getContactId() {
        return contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.contact_id
     *
     * @param contactId the value for contact.contact_id
     *
     * @mbg.generated
     */
    public void setContactId(Integer contactId) {
        this.contactId = contactId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.admin_id
     *
     * @return the value of contact.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.admin_id
     *
     * @param adminId the value for contact.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.telephone
     *
     * @return the value of contact.telephone
     *
     * @mbg.generated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.telephone
     *
     * @param telephone the value for contact.telephone
     *
     * @mbg.generated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.phone
     *
     * @return the value of contact.phone
     *
     * @mbg.generated
     */
    public Integer getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.phone
     *
     * @param phone the value for contact.phone
     *
     * @mbg.generated
     */
    public void setPhone(Integer phone) {
        this.phone = phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.address
     *
     * @return the value of contact.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.address
     *
     * @param address the value for contact.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.wx
     *
     * @return the value of contact.wx
     *
     * @mbg.generated
     */
    public String getWx() {
        return wx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.wx
     *
     * @param wx the value for contact.wx
     *
     * @mbg.generated
     */
    public void setWx(String wx) {
        this.wx = wx == null ? null : wx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.qq
     *
     * @return the value of contact.qq
     *
     * @mbg.generated
     */
    public String getQq() {
        return qq;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.qq
     *
     * @param qq the value for contact.qq
     *
     * @mbg.generated
     */
    public void setQq(String qq) {
        this.qq = qq == null ? null : qq.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contact.QR_code
     *
     * @return the value of contact.QR_code
     *
     * @mbg.generated
     */
    public String getQrCode() {
        return qrCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contact.QR_code
     *
     * @param qrCode the value for contact.QR_code
     *
     * @mbg.generated
     */
    public void setQrCode(String qrCode) {
        this.qrCode = qrCode == null ? null : qrCode.trim();
    }
}