package com.syd.goods.model;

import java.util.Date;

public class EnterpriseVideoModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.video_id
     *
     * @mbg.generated
     */
    private Integer videoId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.video_link
     *
     * @mbg.generated
     */
    private String videoLink;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.video_title
     *
     * @mbg.generated
     */
    private String videoTitle;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.last_update
     *
     * @mbg.generated
     */
    private Date lastUpdate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.status
     *
     * @mbg.generated
     */
    private String status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column enterprise_video.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.video_id
     *
     * @return the value of enterprise_video.video_id
     *
     * @mbg.generated
     */
    public Integer getVideoId() {
        return videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.video_id
     *
     * @param videoId the value for enterprise_video.video_id
     *
     * @mbg.generated
     */
    public void setVideoId(Integer videoId) {
        this.videoId = videoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.video_link
     *
     * @return the value of enterprise_video.video_link
     *
     * @mbg.generated
     */
    public String getVideoLink() {
        return videoLink;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.video_link
     *
     * @param videoLink the value for enterprise_video.video_link
     *
     * @mbg.generated
     */
    public void setVideoLink(String videoLink) {
        this.videoLink = videoLink == null ? null : videoLink.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.video_title
     *
     * @return the value of enterprise_video.video_title
     *
     * @mbg.generated
     */
    public String getVideoTitle() {
        return videoTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.video_title
     *
     * @param videoTitle the value for enterprise_video.video_title
     *
     * @mbg.generated
     */
    public void setVideoTitle(String videoTitle) {
        this.videoTitle = videoTitle == null ? null : videoTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.create_time
     *
     * @return the value of enterprise_video.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.create_time
     *
     * @param createTime the value for enterprise_video.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.last_update
     *
     * @return the value of enterprise_video.last_update
     *
     * @mbg.generated
     */
    public Date getLastUpdate() {
        return lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.last_update
     *
     * @param lastUpdate the value for enterprise_video.last_update
     *
     * @mbg.generated
     */
    public void setLastUpdate(Date lastUpdate) {
        this.lastUpdate = lastUpdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.status
     *
     * @return the value of enterprise_video.status
     *
     * @mbg.generated
     */
    public String getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.status
     *
     * @param status the value for enterprise_video.status
     *
     * @mbg.generated
     */
    public void setStatus(String status) {
        this.status = status == null ? null : status.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column enterprise_video.admin_id
     *
     * @return the value of enterprise_video.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column enterprise_video.admin_id
     *
     * @param adminId the value for enterprise_video.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}