package com.syd.goods.model;

public class GoodsKindModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_kind.goods_kind_id
     *
     * @mbg.generated
     */
    private Integer goodsKindId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_kind.goods_kind_name
     *
     * @mbg.generated
     */
    private String goodsKindName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_kind.goods_kind_flag
     *
     * @mbg.generated
     */
    private String goodsKindFlag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column goods_kind.admin_id
     *
     * @mbg.generated
     */
    private Integer adminId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_kind.goods_kind_id
     *
     * @return the value of goods_kind.goods_kind_id
     *
     * @mbg.generated
     */
    public Integer getGoodsKindId() {
        return goodsKindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_kind.goods_kind_id
     *
     * @param goodsKindId the value for goods_kind.goods_kind_id
     *
     * @mbg.generated
     */
    public void setGoodsKindId(Integer goodsKindId) {
        this.goodsKindId = goodsKindId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_kind.goods_kind_name
     *
     * @return the value of goods_kind.goods_kind_name
     *
     * @mbg.generated
     */
    public String getGoodsKindName() {
        return goodsKindName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_kind.goods_kind_name
     *
     * @param goodsKindName the value for goods_kind.goods_kind_name
     *
     * @mbg.generated
     */
    public void setGoodsKindName(String goodsKindName) {
        this.goodsKindName = goodsKindName == null ? null : goodsKindName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_kind.goods_kind_flag
     *
     * @return the value of goods_kind.goods_kind_flag
     *
     * @mbg.generated
     */
    public String getGoodsKindFlag() {
        return goodsKindFlag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_kind.goods_kind_flag
     *
     * @param goodsKindFlag the value for goods_kind.goods_kind_flag
     *
     * @mbg.generated
     */
    public void setGoodsKindFlag(String goodsKindFlag) {
        this.goodsKindFlag = goodsKindFlag == null ? null : goodsKindFlag.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column goods_kind.admin_id
     *
     * @return the value of goods_kind.admin_id
     *
     * @mbg.generated
     */
    public Integer getAdminId() {
        return adminId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column goods_kind.admin_id
     *
     * @param adminId the value for goods_kind.admin_id
     *
     * @mbg.generated
     */
    public void setAdminId(Integer adminId) {
        this.adminId = adminId;
    }
}