package com.syd.goods.mapper;

import com.syd.goods.model.EnterpriseVideoModel;
import java.util.List;

public interface EnterpriseVideoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_video
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_video
     *
     * @mbg.generated
     */
    int insert(EnterpriseVideoModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_video
     *
     * @mbg.generated
     */
    EnterpriseVideoModel selectByPrimaryKey(Integer videoId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_video
     *
     * @mbg.generated
     */
    List<EnterpriseVideoModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table enterprise_video
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(EnterpriseVideoModel record);
}