package com.syd.goods.mapper;

import com.syd.goods.model.GoodsOrderModel;
import java.util.List;

public interface GoodsOrderMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated
     */
    int insert(GoodsOrderModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated
     */
    GoodsOrderModel selectByPrimaryKey(Integer orderId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated
     */
    List<GoodsOrderModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_order
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsOrderModel record);
}