package com.syd.goods.mapper;

import com.syd.goods.model.GoodsKindModel;
import java.util.List;

public interface GoodsKindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_kind
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer goodsKindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_kind
     *
     * @mbg.generated
     */
    int insert(GoodsKindModel record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_kind
     *
     * @mbg.generated
     */
    GoodsKindModel selectByPrimaryKey(Integer goodsKindId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_kind
     *
     * @mbg.generated
     */
    List<GoodsKindModel> selectAll();

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table goods_kind
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(GoodsKindModel record);

    /**
     * 通过goodkings model 来查询集合
     * @param goodsKindModel
     * @return
     */
    List<GoodsKindModel> selectBygoodsKindModel(GoodsKindModel goodsKindModel);
}